export interface ISkills {
    acrobatics: boolean,
    animalHandling: boolean,
    arcana: boolean,
    athletics: boolean,
    deception: boolean,
    history: boolean,
    insight: boolean,
    intimidation: boolean,
    investigation: boolean,
    medicine: boolean,
    nature: boolean,
    perception: boolean,
    performance: boolean,
    persuassion: boolean,
    religion: boolean,
    sleightOfHand: boolean,
    stealth: boolean,
    survival: boolean,
}